import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Bookmark, Check, ChevronDown, Info, Leaf, Plus, Scale, X } from 'lucide-react';
import { toast } from 'sonner';
import { explainComparison, formatValue, METRICS, NUTRIENTS, money } from '@shared/comparison';
import type { Metric, NutrientKey, Product } from '@shared/models';
import type { IngredientCard } from '@shared/ingredient-guide';
import { useShelf } from '@/features/shelf/store';
import { useProducts } from '@/features/catalog/queries';
import { ProductArt } from '@/components/product-art';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { ErrorState, LoadingState } from '@/components/page-state';
import { ProductDialog } from '@/features/catalog/product-dialog';
import { ManualProductDialog } from '@/features/catalog/manual-product-dialog';
import { IngredientDialog } from '@/features/guide/guide-page';
import { cn } from '@/lib/utils';

export function ComparisonPage() {
  const { state, setState, toggleSelected, toggleSaved } = useShelf(); const { items, loading, error, retry } = useProducts(state.selected);
  const [full, setFull] = useState(false); const [detail, setDetail] = useState<Product | null>(null); const [manual, setManual] = useState<Product | null>(null); const [ingredient, setIngredient] = useState<IngredientCard | null>(null);
  const [bowlDraft, setBowlDraft] = useState(String(state.bowl)); useEffect(() => setBowlDraft(String(state.bowl)), [state.bowl]);
  const summary = explainComparison(items, state.metric, state.usual); const grams = state.basis === '100' ? 100 : state.bowl;
  const rows: (NutrientKey | 'price')[] = full ? ['fibre', 'sugars', 'sodium', 'price', 'protein', 'saturated', 'fat', 'carbs', 'calories', 'addedSugars'] : ['fibre', 'sugars', 'sodium', 'price'];
  function saveComparison() {
    if (state.selected.length < 2) return;
    const signature = (value: { selected: string[]; metric: string; basis: string; bowl: number; usual: string }) => JSON.stringify([value.selected, value.metric, value.basis, value.bowl, value.usual]);
    if (state.decisions.some((decision) => signature(decision) === signature(state))) { toast.info('This comparison is already on your shelf.'); return; }
    setState((old) => ({ ...old, decisions: [{ id: `decision-${crypto.randomUUID()}`, selected: [...old.selected], metric: old.metric, basis: old.basis, bowl: old.bowl, usual: old.usual, created: new Date().toISOString() }, ...old.decisions].slice(0, 100) }));
    toast.success('Comparison saved to My shelf.');
  }
  return <>
    <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow mb-3">Your everyday, considered</p><h1 className="page-title">Same aisle. <span className="text-[#7c8e64]">Clearer choice.</span></h1><p className="mt-3 text-sm text-muted-foreground">Compare what matters to you. Leave the guesswork on the shelf.</p></div><Button asChild variant="outline"><Link to="/shop"><Plus />Add a product</Link></Button></div>
    <Card className="mb-6 flex flex-wrap items-center justify-between gap-4 p-4 sm:px-5"><div><p className="text-xs font-semibold">What matters most today?</p><p className="mt-1 text-[11px] text-muted-foreground">One priority. An honest trade-off.</p></div><div className="flex flex-wrap gap-2" aria-label="Comparison priority">{(Object.keys(METRICS) as Metric[]).map((metric) => <Button size="sm" key={metric} variant={state.metric === metric ? 'default' : 'outline'} aria-pressed={state.metric === metric} onClick={() => setState((old) => ({ ...old, metric }))}>{state.metric === metric && <Check />}{METRICS[metric].label}</Button>)}</div></Card>
    {loading ? <LoadingState /> : error ? <ErrorState error={error} retry={retry} /> : <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_290px]">
      <div className="min-w-0 space-y-5">
        <div className={cn('grid gap-4', items.length < 2 ? 'grid-cols-1 sm:grid-cols-2' : items.length > 2 ? 'grid-cols-2 2xl:grid-cols-4' : 'grid-cols-2')}>{items.map((product) => <Card key={product.id} className="min-w-0 overflow-hidden p-3"><div className="relative"><button className="block w-full" aria-label={`View ${product.name}`} onClick={() => setDetail(product)}><ProductArt product={product} className="h-44 sm:h-52" /></button><Button aria-label={`Remove ${product.name}`} variant="ghost" size="icon" className="absolute right-0 top-0 size-8 rounded-full bg-white/80" onClick={() => toggleSelected(product.id)}><X /></Button><Badge className="absolute bottom-2 left-2 bg-white/95">{state.usual === product.id ? 'Your usual' : 'The alternative'}</Badge></div><div className="px-1 pb-1 pt-4"><p className="eyebrow mb-1">{product.brand}</p><h2 className="min-h-10 text-sm font-semibold sm:min-h-0">{product.name}</h2><p className="mt-2 text-sm font-semibold">{money(product.price)} <span className="text-[10px] font-normal text-muted-foreground">/ {product.weight ?? '?'} g</span></p><div className="mt-3 flex flex-wrap items-center justify-between gap-1"><Button variant="link" size="sm" className="h-8 px-0 text-[11px]" onClick={() => setDetail(product)}>View label & price</Button><Button aria-label={`${state.saved.includes(product.id) ? 'Unsave' : 'Save'} ${product.name}`} aria-pressed={state.saved.includes(product.id)} variant="ghost" size="icon" className="size-8" onClick={() => toggleSaved(product.id)}><Bookmark fill={state.saved.includes(product.id) ? 'currentColor' : 'none'} /></Button></div></div></Card>)}{items.length < 2 && <Link to="/shop" className="flex min-h-64 flex-col items-center justify-center gap-3 rounded-2xl border border-dashed text-sm text-muted-foreground"><Plus className="size-7" />Choose another product</Link>}</div>
        {items.length > 0 && <Card className="overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4 sm:px-5"><div><h2 className="text-sm font-semibold">The meaningful differences</h2><p className="mt-1 text-[10px] text-muted-foreground">Same quantity. As sold. No hidden overall score.</p></div><div className="flex flex-wrap items-center gap-2"><Button size="sm" variant={state.basis === '100' ? 'secondary' : 'ghost'} aria-pressed={state.basis === '100'} onClick={() => setState((old) => ({ ...old, basis: '100' }))}>Per 100 g</Button><Button size="sm" variant={state.basis === 'bowl' ? 'secondary' : 'ghost'} aria-pressed={state.basis === 'bowl'} onClick={() => setState((old) => ({ ...old, basis: 'bowl' }))}>My bowl</Button>{state.basis === 'bowl' && <label className="flex items-center gap-1 text-xs"><Input aria-label="Bowl size in grams" type="number" className="h-9 w-20" min="10" max="200" value={bowlDraft} onChange={(event) => setBowlDraft(event.target.value)} onBlur={() => { const value = Number(bowlDraft); if (Number.isFinite(value) && value >= 10 && value <= 200) setState((old) => ({ ...old, bowl: value })); else { setBowlDraft(String(state.bowl)); toast.error('Choose a bowl between 10 and 200 grams.'); } }} onKeyDown={(event) => { if (event.key === 'Enter') event.currentTarget.blur(); }} />g</label>}</div></div>
          <div className="table-scroll px-3 sm:px-5" tabIndex={0} role="region" aria-label="Nutrition comparison"><table className="nutrition-table"><caption className="sr-only">Nutrition and price per {grams} grams</caption><thead><tr><th scope="col">Per {grams} g</th>{items.map((product) => <th scope="col" key={product.id}>{product.brand}</th>)}</tr></thead><tbody>{rows.map((key) => <tr key={key} className={key === state.metric ? 'metric-focus' : ''}><th scope="row">{NUTRIENTS[key].label}{key === state.metric && <span className="ml-1 text-primary" aria-label="Your priority">●</span>}</th>{items.map((product) => <td key={product.id} className={cn(key === state.metric && summary.status === 'ready' && summary.winners[0].id === product.id && 'font-semibold text-primary')}>{formatValue(product, key, grams)}</td>)}</tr>)}</tbody></table></div>
          <div className="flex items-center justify-between gap-3 border-t px-5 py-3"><p className="text-[10px] text-muted-foreground">Missing data stays unknown, never zero.</p><Button variant="ghost" size="sm" onClick={() => setFull(!full)}>{full ? 'Less detail' : 'Full nutrition'}<ChevronDown className={full ? 'rotate-180' : ''} /></Button></div>
        </Card>}
        <details className="rounded-xl border bg-white px-5 py-4 text-xs"><summary className="cursor-pointer font-medium">Where these numbers come from</summary><div className="mt-4 space-y-4 text-muted-foreground">{items.map((product) => <div key={product.id}><p className="font-semibold text-foreground">{product.name}</p><p>Nutrition: {product.provenance?.nutrition.label ?? product.source}</p><p>Price: {product.provenance?.price.label ?? product.source}</p><p>{product.provenance?.nutrition.verifiedAt ? `Nutrition verified ${product.provenance.nutrition.verifiedAt}` : 'Nutrition not verified against a current package.'}</p></div>)}<p>Seed products, packaging, prices and quantities are fictional. User-entered values remain unverified. Ingredient explanations are separate from these numerical comparisons.</p></div></details>
      </div>
      <aside className="space-y-4 xl:sticky xl:top-6"><Card className="overflow-hidden"><div className="bg-[#f0f4e7] p-5"><p className="eyebrow mb-4 flex items-center gap-2 text-primary"><Leaf className="size-4" />A little perspective</p><h2 className="font-serif text-[25px] leading-tight tracking-tight" data-testid="decision-title">{summary.title}</h2><p className="mt-4 text-xs leading-6 text-muted-foreground">{summary.body}</p></div><div className="space-y-4 p-5">{summary.tradeoffs.length > 0 && <><div className="flex items-center gap-2 text-xs font-semibold"><Scale className="size-4" />The trade-offs</div><p className="text-[10px] text-muted-foreground">Compared with {'comparedWith' in summary ? summary.comparedWith : 'your other option'}:</p><ul className="space-y-3">{summary.tradeoffs.map((tradeoff) => <li key={tradeoff} className="text-xs leading-5 text-muted-foreground">{tradeoff}</li>)}</ul></>}<Button className="w-full" disabled={items.length < 2} onClick={saveComparison}><Bookmark />Save comparison</Button><p className="flex gap-2 text-[10px] leading-5 text-muted-foreground"><Info className="mt-1 size-3 shrink-0" />A match for your priority—not a verdict about health or allergy safety.</p></div></Card><p className="px-2 text-[10px] leading-5 text-muted-foreground">Sometimes both options are perfectly reasonable. You do not need to optimize every purchase.</p></aside>
    </div>}
    <ProductDialog product={detail} onClose={() => setDetail(null)} onEdit={(product) => { setDetail(null); setManual(product); }} onIngredient={(card) => { setDetail(null); setIngredient(card); }} /><ManualProductDialog open={!!manual} initial={manual ?? undefined} onClose={() => setManual(null)} /><IngredientDialog card={ingredient} onClose={() => setIngredient(null)} />
  </>;
}
