import { useRef, useState } from 'react';
import { Download, Upload, RotateCcw, Database, LockKeyhole } from 'lucide-react';
import { toast } from 'sonner';
import { decodeShelf, defaultShelf, type Shelf } from '@shared/shelf';
import { useShelf, exportShelf } from './store';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
export function SettingsPage() {
  const { state, setState } = useShelf(); const input = useRef<HTMLInputElement>(null); const [pending, setPending] = useState<Shelf | null>(null); const [reset, setReset] = useState(false);
  return <><div className="mb-8"><p className="eyebrow mb-3">A small, transparent beginning</p><h1 className="page-title">Your data. <span className="text-[#7c8e64]">No surprises.</span></h1></div><div className="grid gap-5 lg:grid-cols-2"><Card className="space-y-4 p-6"><LockKeyhole className="size-6 text-primary" /><h2 className="text-lg font-semibold">Your shelf stays on this browser.</h2><p className="text-sm leading-6 text-muted-foreground">Bookmarks, your usual cereal, manual entries, prices and saved comparisons live in local browser storage. There are no accounts, tracking scripts or cloud-synced personal records in this version. Clearing browser data removes your shelf.</p><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => exportShelf(state)}><Download />Export my shelf</Button><Button variant="outline" onClick={() => input.current?.click()}><Upload />Import a shelf</Button><input ref={input} className="sr-only" type="file" accept="application/json,.json" aria-label="Import shelf JSON" onChange={async (event) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; if (file.size > 2 * 1024 * 1024) { toast.error('Choose a JSON export smaller than 2 MB.'); return; } try { setPending(decodeShelf(JSON.parse(await file.text()))); } catch (error) { toast.error(error instanceof Error ? error.message : 'Invalid shelf export.'); } }} /></div><p className="text-xs leading-5 text-muted-foreground">Exports from the original single-file prototype are supported. When moving from a downloaded HTML file, export there first and import here. Photos are never included.</p></Card>
      <Card className="space-y-4 p-6"><Database className="size-6 text-primary" /><h2 className="text-lg font-semibold">A real API. A fictional starter catalog.</h2><p className="text-sm leading-6 text-muted-foreground">The shared catalog is read from Cloudflare D1 through a read-only Worker API. Eight fictional cereals retain the original prototype’s examples, including ties and missing information. Prices are sample observations, not live retailer feeds.</p><p className="text-sm leading-6 text-muted-foreground">Barcode lookup recognizes DEMO001–DEMO008. Label photos are local previews for manual entry; no OCR, AI analysis or external product database is connected.</p><a href="/api/health" target="_blank" rel="noreferrer" className="text-sm text-primary underline">Check API health</a></Card>
      <Card className="space-y-4 p-6 lg:col-span-2"><h2 className="text-lg font-semibold">Start fresh</h2><p className="text-sm text-muted-foreground">Reset your local shelf, preferences and manual entries to the sample comparison. This does not change D1 or anyone else’s data.</p><Button variant="outline" onClick={() => setReset(true)}><RotateCcw />Reset this browser’s demo</Button></Card></div>
      <Dialog open={!!pending} onOpenChange={(open) => { if (!open) setPending(null); }}><DialogContent><DialogHeader><DialogTitle>Replace your local shelf?</DialogTitle><DialogDescription>This import contains {pending?.saved.length} saved products, {pending?.custom.length} manual entries and {pending?.decisions.length} comparisons. Your current local shelf will be replaced.</DialogDescription></DialogHeader><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => exportShelf(state)}>Export current shelf first</Button><Button onClick={() => { if (pending) setState(pending); setPending(null); toast.success('Your shelf has been imported.'); }}>Replace my local shelf</Button></div></DialogContent></Dialog>
      <Dialog open={reset} onOpenChange={setReset}><DialogContent><DialogHeader><DialogTitle>Start fresh?</DialogTitle><DialogDescription>This permanently removes manual entries, saved comparisons and local price changes from this browser. Export first to keep a copy.</DialogDescription></DialogHeader><div className="flex gap-2"><Button variant="outline" onClick={() => setReset(false)}>Keep my data</Button><Button variant="destructive" onClick={() => { setState(defaultShelf()); setReset(false); toast.success('The sample pair is restored.'); }}>Reset local data</Button></div></DialogContent></Dialog>
    </>;
}
