import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowRight, Bookmark, Plus, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { METRICS, money } from '@shared/comparison';
import type { Product } from '@shared/models';
import type { IngredientCard } from '@shared/ingredient-guide';
import { useShelf } from './store';
import { useProducts } from '@/features/catalog/queries';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';
import { ProductArt } from '@/components/product-art';
import { LoadingState, ErrorState } from '@/components/page-state';
import { ProductDialog } from '@/features/catalog/product-dialog';
import { ManualProductDialog } from '@/features/catalog/manual-product-dialog';
import { IngredientDialog } from '@/features/guide/guide-page';
export function ShelfPage() {
  const { state, setState, toggleSaved } = useShelf(); const navigate = useNavigate();
  const { items, loading, error, retry } = useProducts(state.saved); const [tab, setTab] = useState<'products' | 'decisions'>('products');
  const [detail, setDetail] = useState<Product | null>(null); const [manual, setManual] = useState<Product | null>(null); const [ingredient, setIngredient] = useState<IngredientCard | null>(null);
  return <><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow mb-3">Keep the useful things</p><h1 className="page-title">Your shelf. <span className="text-[#7c8e64]">Your usuals.</span></h1><p className="mt-3 text-sm text-muted-foreground">Familiar favourites and decisions worth remembering. Saved on this browser.</p></div><Button variant="outline" asChild><Link to="/shop"><Plus />Find a product</Link></Button></div><div className="mb-6 flex gap-2"><Button variant={tab === 'products' ? 'default' : 'outline'} onClick={() => setTab('products')}>Saved products ({state.saved.length})</Button><Button variant={tab === 'decisions' ? 'default' : 'outline'} onClick={() => setTab('decisions')}>Saved comparisons ({state.decisions.length})</Button></div>
    {tab === 'products' ? loading ? <LoadingState /> : error ? <ErrorState error={error} retry={retry} /> : <div className="grid gap-4 md:grid-cols-2">{items.map((product) => <Card key={product.id} className="flex min-w-0 gap-4 p-4"><button onClick={() => setDetail(product)} className="shrink-0" aria-label={`View ${product.name}`}><ProductArt product={product} className="h-36 w-24" /></button><div className="flex min-w-0 flex-1 flex-col items-start justify-center gap-2"><p className="eyebrow">{product.brand}</p><h2 className="text-sm font-semibold">{product.name}</h2>{state.usual === product.id && <Badge>Your usual</Badge>}<p className="text-xs text-muted-foreground">{money(product.price)} · {product.weight ?? '?'} g</p><Button variant="link" size="sm" className="px-0" onClick={() => setDetail(product)}>View label <ArrowRight /></Button></div><Button variant="ghost" size="icon" aria-label={`Unsave ${product.name}`} onClick={() => toggleSaved(product.id)}><Bookmark fill="currentColor" /></Button></Card>)}{!items.length && <Card className="space-y-4 p-10 text-center md:col-span-2"><h2 className="font-serif text-2xl">A little space for your favourites.</h2><p className="text-sm text-muted-foreground">Bookmark products from the grocery aisle to keep them here.</p><Button asChild><Link to="/shop">Explore the aisle</Link></Button></Card>}</div> : <div className="space-y-4">{state.decisions.map((decision) => <Card key={decision.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="text-sm font-semibold">{METRICS[decision.metric].label} · {decision.selected.length} products</p><p className="mt-1 text-xs text-muted-foreground">Saved {new Date(decision.created).toLocaleDateString('en-CA')} · {decision.basis === '100' ? 'Per 100 g' : `${decision.bowl} g bowl`}</p><p className="mt-2 text-[11px] text-muted-foreground">Reopens using current catalog values and your local edits.</p></div><div className="flex gap-2"><Button onClick={() => { setState((old) => ({ ...old, selected: decision.selected, metric: decision.metric, basis: decision.basis, bowl: decision.bowl, usual: decision.usual })); navigate('/compare'); }}>Reopen comparison <ArrowRight /></Button><Button variant="ghost" size="icon" aria-label="Delete saved comparison" onClick={() => { setState((old) => ({ ...old, decisions: old.decisions.filter((item) => item.id !== decision.id) })); toast.success('Saved comparison removed.'); }}><Trash2 /></Button></div></Card>)}{!state.decisions.length && <Card className="space-y-3 p-10 text-center"><h2 className="font-serif text-2xl">No decisions saved yet.</h2><p className="text-sm text-muted-foreground">Use “Save comparison” when you find a useful trade-off.</p><Button asChild><Link to="/compare">Start a comparison</Link></Button></Card>}</div>}
    <ProductDialog product={detail} onClose={() => setDetail(null)} onEdit={(product) => { setDetail(null); setManual(product); }} onIngredient={(card) => { setDetail(null); setIngredient(card); }} /><ManualProductDialog open={!!manual} initial={manual ?? undefined} onClose={() => setManual(null)} /><IngredientDialog card={ingredient} onClose={() => setIngredient(null)} />
  </>;
}
